#账号密码
server:
  port: 8080
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/648695657//spring-cloud-zlm-config
          search-paths:
            - foo #路径
            - bar #路径
          clone-on-start: true #启动时加载所有配置信息
  application:
    name: config-server-eureka
eureka:
  client:
    service-url:
      # 指定eureka server通信地址，注意/eureka/小尾巴不能少
      defaultZone: http://localhost:8761/eureka/
  instance:
    ip-address: true # 是否注册IP到eureka server，如不指定或设为false，那就会注册主机名到eureka server
